# ==============================================================================
# Script:           config.yaml
# Purpose:          Pipeline configurations
# Author:           Sophia Mengjia Li
# Affiliation:      CCG Lab, Princess Margaret Cancer Center, UHN, UofT
# Date:             06/23/2026
# ==============================================================================

patch_size: 256

paths:
  inputs:
    patch_dir: /cluster/projects/kumargroup/sean/Methylation_Generation/m24_patches
    embedding_dir: /cluster/projects/kumargroup/sean/Methylation_Generation/m24_embeddings # UNI embeddings for input into the proteomics model

  outputs:
    metadata: /cluster/projects/kumargroup/sophia/wsi-attention-composition/metadata
    inference_dir: /cluster/projects/kumargroup/sophia/wsi-attention-composition/predictions
    composition_dir: /cluster/projects/kumargroup/sophia/wsi-attention-composition/compositions
    attention_dir: /cluster/projects/kumargroup/sophia/wsi-attention-composition/attention
    merged_dir: /cluster/projects/kumargroup/sophia/wsi-attention-composition/merged

models:
  hovernet: # Model path added directly in SLURM submission script
    model: /cluster/projects/kumargroup/sophia/hover_net
    weights: /cluster/projects/kumargroup/sophia/hovernet_fast_pannuke_type_tf2pytorch.tar
    mode: fast       # 'fast' or 'original'
    nr_types: 6      # Default CoNSeP types
    n_workers: 4
    batch_size: 8

  protein_model: /cluster/projects/kumargroup/sean/results/05-inference/all_data_combined/05_train_all_data_combined_20260617_J6829500/cov0

results:
  correlation_results: results/correlation_results.txt

composition:
  n_workers: 4

inference:
  batch_size: 32
  n_workers: 3

# [END]