# ==============================================================================
# Script:           composition.py
# Purpose:          Extracts patch compositions from HoVer-net output
# Author:           Sophia Mengjia Li
# Affiliation:      CCG Lab, Princess Margaret Cancer Center, UHN, UofT
# Date:             07/02/2026
# ==============================================================================

import pandas as pd
import numpy as np

from pathlib import Path
from models.hovernet.post_proc import process as hovernet_postproc
from concurrent.futures import ProcessPoolExecutor

from src.utils import setup_logger
from src.io import load_sample_predictions, save_sample_compositions

logger = setup_logger(__name__)

PANNUKE_CLASSES = {
    0: "background",
    1: "neoplastic",
    2: "inflammatory",
    3: "connective",
    4: "dead",
    5: "epithelial"
}
NR_TYPES = 6


def extract_sample_compositions(pool: ProcessPoolExecutor,
                                src_path : Path,
                                dst_path : Path,
                                n_workers: int) -> None: 
    """
    Loads a sample's HoVer-net predictions (.h5) and extracts is per-patch 
    composition table (row per patch). Saves the compositions to the 
    destination path provided.
    """

    sample_id = src_path.stem.removesuffix("_predictions")
    logger.info(f"- | Beginning to process sample {sample_id}")

    # Load raw nucleus-level predictions as generated by HoVer-net
    predictions = load_sample_predictions(src_path)
    tasks = list(predictions.values())
    logger.info(f"- | - Detected {len(predictions.keys())} patches")
    
    # Parallelize computation across tiles
    chunksize = max(1, len(tasks) // (n_workers * 4))
    records = list(pool.map(extract_composition, tasks, chunksize = chunksize))
    compositions = pd.DataFrame.from_records(records)

    # Save all sample patch compositions together into a parquet
    save_sample_compositions(compositions, dst_path)


def extract_composition(predictions: dict, 
                        nr_types: int = NR_TYPES) -> dict:
    """
    Run HoVer-net post-processing per patch to get per-nucleus instance types, 
    then aggregate into per-patch cell-type compositions.
    """

    base_result = {'patch_name': predictions['patch_name']}
    empty_comp  = {name: 0 for name in PANNUKE_CLASSES.values() 
                   if name != 'background'}

    try:
        patch_dict = {
            "np": np.transpose(predictions["np"], (1, 2, 0)),
            "hv": np.transpose(predictions["hv"], (1, 2, 0)),
            "tp": np.transpose(predictions["tp"], (1, 2, 0)),
        }

        logger.info("Patch dict items:")
        for k, v in patch_dict.items():
            logger.info(
                "%s: type=%s shape=%s dtype=%s",
                k,
                type(v),
                getattr(v, "shape", None),
                getattr(v, "dtype", None),
            )

        logger.info("Predictions items:g")
        for k, v in predictions.items():
            logger.info(
                "%s: %s %s",
                k,
                type(v),
                getattr(v, "shape", None),
            )

        # Apply the provided watershed algorithm
        _, inst_info_dict = hovernet_postproc(
            patch_dict, 
            nr_types         = nr_types,
            return_centroids = False
        )
        
        # Aggregate cell-type compositions
        counts = empty_comp.copy()
        for inst_info in inst_info_dict.values():

            # Extract the corresponding type from established classes
            type_idx = inst_info["type"]
            type_name = PANNUKE_CLASSES.get(type_idx, f"type_{type_idx}")
            if type_name in counts: counts[type_name] += 1

        counts["total_cells"] = sum(counts.values())

        logger.info("- | - Successfully extracted patch compositions")
        return {**base_result, **counts}
    
    except Exception: 
        logger.exception(f"- | - [ERROR] Failed to extracted patch compositions")
        return {**base_result, **empty_comp, 'total_cells': 0}

# [END]